# Importing Libraries and Dataset

In [105]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [145]:
data = pd.read_csv("ParisHousing.csv")
data.head()

squareMeters  numberOfRooms  hasYard  hasPool  floors  cityCode  \
0         75523              3        0        1      63      9373   
1         80771             39        1        1      98     39381   
2         55712             58        0        1      19     34457   
3         32316             47        0        0       6     27939   
4         70429             19        1        1      90     38045   

   cityPartRange  numPrevOwners  made  isNewBuilt  hasStormProtector  \
0              3              8  2005           0                  1   
1              8              6  2015           1                  0   
2              6              8  2021           0                  0   
3             10              4  2012           0                  1   
4              3              7  1990           1                  0   

   basement  attic  garage  hasStorageRoom  hasGuestRoom      price  
0      4313   9005     956               0             7  7559081.5  
1      3653   2436     128               1             2  8085989.5  
2      2937   8852     135               1             9  5574642.1  
3       659   7141     359               0             3  3232561.2  
4      8435   2429     292               1             4  7055052.0

In [146]:
data.shape

(10000, 17)

# Data Exploring and Cleaning

In [147]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   squareMeters       10000 non-null  int64  
 1   numberOfRooms      10000 non-null  int64  
 2   hasYard            10000 non-null  int64  
 3   hasPool            10000 non-null  int64  
 4   floors             10000 non-null  int64  
 5   cityCode           10000 non-null  int64  
 6   cityPartRange      10000 non-null  int64  
 7   numPrevOwners      10000 non-null  int64  
 8   made               10000 non-null  int64  
 9   isNewBuilt         10000 non-null  int64  
 10  hasStormProtector  10000 non-null  int64  
 11  basement           10000 non-null  int64  
 12  attic              10000 non-null  int64  
 13  garage             10000 non-null  int64  
 14  hasStorageRoom     10000 non-null  int64  
 15  hasGuestRoom       10000 non-null  int64  
 16  price              1000

In [148]:
data.describe()

squareMeters  numberOfRooms       hasYard       hasPool        floors  \
count   10000.00000   10000.000000  10000.000000  10000.000000  10000.000000   
mean    49870.13120      50.358400      0.508700      0.496800     50.276300   
std     28774.37535      28.816696      0.499949      0.500015     28.889171   
min        89.00000       1.000000      0.000000      0.000000      1.000000   
25%     25098.50000      25.000000      0.000000      0.000000     25.000000   
50%     50105.50000      50.000000      1.000000      0.000000     50.000000   
75%     74609.75000      75.000000      1.000000      1.000000     76.000000   
max     99999.00000     100.000000      1.000000      1.000000    100.000000   

           cityCode  cityPartRange  numPrevOwners         made    isNewBuilt  \
count  10000.000000   10000.000000   10000.000000  10000.00000  10000.000000   
mean   50225.486100       5.510100       5.521700   2005.48850      0.499100   
std    29006.675799       2.872024       2.856667      9.30809      0.500024   
min        3.000000       1.000000       1.000000   1990.00000      0.000000   
25%    24693.750000       3.000000       3.000000   1997.00000      0.000000   
50%    50693.000000       5.000000       5.000000   2005.50000      0.000000   
75%    75683.250000       8.000000       8.000000   2014.00000      1.000000   
max    99953.000000      10.000000      10.000000   2021.00000      1.000000   

       hasStormProtector      basement        attic       garage  \
count       10000.000000  10000.000000  10000.00000  10000.00000   
mean            0.499900   5033.103900   5028.01060    553.12120   
std             0.500025   2876.729545   2894.33221    262.05017   
min             0.000000      0.000000      1.00000    100.00000   
25%             0.000000   2559.750000   2512.00000    327.75000   
50%             0.000000   5092.500000   5045.00000    554.00000   
75%             1.000000   7511.250000   7540.50000    777.25000   
max             1.000000  10000.000000  10000.00000   1000.00000   

       hasStorageRoom  hasGuestRoom         price  
count    10000.000000   10000.00000  1.000000e+04  
mean         0.503000       4.99460  4.993448e+06  
std          0.500016       3.17641  2.877424e+06  
min          0.000000       0.00000  1.031350e+04  
25%          0.000000       2.00000  2.516402e+06  
50%          1.000000       5.00000  5.016180e+06  
75%          1.000000       8.00000  7.469092e+06  
max          1.000000      10.00000  1.000677e+07

In [113]:
data['Date'] = data['Date'].str[-4:]
data['Date']

0       2010
1       2010
2       2010
3       2010
4       2010
        ... 
6430    2012
6431    2012
6432    2012
6433    2012
6434    2012
Name: Date, Length: 6435, dtype: object

In [114]:
data['Date'].unique()

array(['2010', '2011', '2012'], dtype=object)

In [149]:
X = data.iloc[:, :-1]
Y = data.iloc[:, -1]

In [150]:
X.shape

(10000, 16)

In [151]:
X.head()

squareMeters  numberOfRooms  hasYard  hasPool  floors  cityCode  \
0         75523              3        0        1      63      9373   
1         80771             39        1        1      98     39381   
2         55712             58        0        1      19     34457   
3         32316             47        0        0       6     27939   
4         70429             19        1        1      90     38045   

   cityPartRange  numPrevOwners  made  isNewBuilt  hasStormProtector  \
0              3              8  2005           0                  1   
1              8              6  2015           1                  0   
2              6              8  2021           0                  0   
3             10              4  2012           0                  1   
4              3              7  1990           1                  0   

   basement  attic  garage  hasStorageRoom  hasGuestRoom  
0      4313   9005     956               0             7  
1      3653   2436     128               1             2  
2      2937   8852     135               1             9  
3       659   7141     359               0             3  
4      8435   2429     292               1             4

In [152]:
Y.shape

(10000,)

In [153]:
Y.head()

0    7559081.5
1    8085989.5
2    5574642.1
3    3232561.2
4    7055052.0
Name: price, dtype: float64

## Data Splitting

In [154]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [155]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [156]:
x_train

array([[ 1.1189976 ,  0.22279829, -1.01460667, ...,  0.70692003,
         1.00025003, -0.93962897],
       [ 1.02094519,  1.2987203 , -1.01460667, ...,  0.72979271,
        -0.99975003, -0.62348178],
       [ 0.99548658,  0.70869855,  0.98560362, ..., -0.84460972,
         1.00025003,  0.32495979],
       ...,
       [ 1.72058417,  0.60457706,  0.98560362, ..., -1.10764548,
         1.00025003, -0.30733459],
       [-1.13900939, -0.15898049,  0.98560362, ..., -0.77980381,
        -0.99975003, -0.93962897],
       [-1.60833026,  1.15989165,  0.98560362, ...,  1.0042648 ,
        -0.99975003,  1.58954856]])

In [157]:
x_test

array([[ 1.04973057, -1.5125598 ,  0.98560362, ...,  1.31685802,
         1.00025003, -1.25577616],
       [-0.43877509,  0.98635584,  0.98560362, ..., -1.48885672,
        -0.99975003,  0.0088126 ],
       [ 1.25714645, -0.50605211,  0.98560362, ...,  0.53918709,
         1.00025003,  0.64110698],
       ...,
       [-1.05513956, -0.99195237,  0.98560362, ..., -0.60825875,
         1.00025003,  0.0088126 ],
       [-0.70684338, -0.29780914,  0.98560362, ..., -1.33637223,
         1.00025003,  1.27340137],
       [ 0.72731323, -1.13078102,  0.98560362, ...,  0.84415608,
         1.00025003,  0.0088126 ]])

# Machine Learning Model

## Linear Regression

In [158]:
from sklearn.linear_model import LinearRegression
model1 = LinearRegression()
model1.fit(x_train, y_train)

LinearRegression()

In [159]:
y_pred1 = model1.predict(x_test)

In [160]:
y_pred1.reshape(-1, 1)

array([[7962638.49058964],
       [3715852.21234054],
       [8553849.80785994],
       ...,
       [1951271.36251268],
       [2945553.06899965],
       [7042691.64493204]])

In [165]:
from sklearn.metrics import mean_absolute_percentage_error, mean_squared_error, r2_score, mean_absolute_error
print(r2_score(y_test, y_pred1)*100)
print(mean_squared_error(y_test, y_pred1))
print(mean_absolute_error(y_test, y_pred1))

99.99995780555567
3695708.440618681
1510.0341808542485


## Decision Tree

In [166]:
from sklearn.tree import DecisionTreeRegressor
model2 = DecisionTreeRegressor()
model2.fit(x_train,y_train)

DecisionTreeRegressor()

In [167]:
y_pred2 = model2.predict(x_test)

In [168]:
y_pred2.reshape(-1,1)

array([[7955735. ],
       [3712504. ],
       [8548531.2],
       ...,
       [1940788. ],
       [2947292.8],
       [7034364. ]])

In [169]:
print(r2_score(y_test, y_pred2)*100)
print(mean_squared_error(y_test, y_pred2))
print(mean_absolute_error(y_test, y_pred2))

99.99963840796214
31670964.455750007
4485.410799999999


## Random Forest

In [170]:
from sklearn.ensemble import RandomForestRegressor
model3 = RandomForestRegressor(n_estimators=150)
model3.fit(x_train, y_train)

RandomForestRegressor(n_estimators=150)

In [171]:
y_pred3 = model3.predict(x_test)

In [172]:
y_pred3.reshape(-1, 1)

array([[7957658.86266666],
       [3711260.03933333],
       [8552872.63      ],
       ...,
       [1953210.87266667],
       [2945254.898     ],
       [7037501.562     ]])

In [173]:
print(r2_score(y_test, y_pred3)*100)
print(mean_squared_error(y_test, y_pred3))
print(mean_absolute_error(y_test, y_pred3))

99.9998173314131
15999495.888230598
3183.829595999891


## XGboost

In [175]:
from xgboost import XGBRegressor
model4 = XGBRegressor()
model4.fit(x_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=None, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...)

In [177]:
y_pred4 = model4.predict(x_test)
y_pred4.reshape(-1,1)

array([[7959535.5],
       [3701309. ],
       [8548792. ],
       ...,
       [1964376.2],
       [2947139. ],
       [7039402.5]], dtype=float32)

In [178]:
print(r2_score(y_test, y_pred4)*100)
print(mean_squared_error(y_test, y_pred4))
print(mean_absolute_error(y_test, y_pred4))

99.99764491691292
206275982.1289253
11687.395852539068


## Neural Network

In [180]:
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense

model5 = Sequential([
    Dense(25, activation='relu', input_dim=16),
    Dense(25, activation='relu'),
    Dense(1, activation='linear')
])

model5.summary()

c:\Users\hadi\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:85: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 25)             │           425 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 25)             │           650 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            26 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,101 (4.30 KB)

 Trainable params: 1,101 (4.30 KB)

 Non-trainable params: 0 (0.00 B)

In [183]:
from keras.losses import MeanSquaredError
model5.compile(optimizer='Adam', loss=MeanSquaredError())

In [184]:
model5.fit(x_train, y_train, epochs=100)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 32692066320384.0000
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 32461448806400.0000
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 33092651712512.0000
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 32077707739136.0000
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 32491509383168.0000
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 32821236203520.0000
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 32993756315648.0000
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 32224172834816.0000
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 32451667689472.0000
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 32315621244928.0000
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 32743362658304.0000
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 31913238593536.0000
Epoch 13/100
250/250 ━━━━

In [185]:
y_pred5 = model5.predict(x_test)

63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step


In [186]:
print(r2_score(y_test, y_pred4)*100)
print(mean_squared_error(y_test, y_pred4))
print(mean_absolute_error(y_test, y_pred4))

99.99764491691292
206275982.1289253
11687.395852539068
